name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.2
            gemfile: Gemfile
          - ruby: 3.1
            gemfile: Gemfile
          - ruby: "3.0"
            gemfile: gemfiles/activerecord61.gemfile
          - ruby: 2.7
            gemfile: gemfiles/activerecord60.gemfile
          - ruby: 2.6
            gemfile: gemfiles/activerecord52.gemfile
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          database: rollup_test
      - uses: ankane/setup-mysql@v1
        with:
          database: rollup_test
      - run: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
      - run: bundle exec rake test
